#!/usr/bin/env python3
"""Generate index pages for KDDs and OQs from their per-file frontmatter.

Reads every ``KDD-*.md`` under ``new-structure/decisions`` and every ``OQ-*.md``
under ``new-structure/open-questions``, extracts the YAML frontmatter, and writes
``index.md`` tables that the MkDocs site links to. Dependency-free: parses only the
scalar frontmatter keys it needs, so it runs anywhere Python 3 is available.

Run from anywhere::

    python new-structure/scripts/build_indexes.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DECISIONS_DIR = REPO_ROOT / "new-structure" / "decisions"
OPEN_QUESTIONS_DIR = REPO_ROOT / "new-structure" / "open-questions"

GENERATED_NOTE = (
    "<!-- Generated by new-structure/scripts/build_indexes.py. Do not edit by hand. -->"
)


def _read_frontmatter(path: Path) -> dict[str, str]:
    """Return the scalar frontmatter keys from a Markdown file."""
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not match:
        return {}
    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        kv = re.match(r"^([A-Za-z0-9_]+):\s*(.*)$", line)
        if not kv:
            continue
        key, value = kv.group(1), kv.group(2).strip()
        fields[key] = value
    return fields


def _id_sort_key(record_id: str) -> tuple[str, int]:
    parts = record_id.split("-", 1)
    prefix = parts[0]
    try:
        number = int(parts[1])
    except (IndexError, ValueError):
        number = 0
    return prefix, number


def _collect(directory: Path, glob: str) -> list[tuple[dict[str, str], Path]]:
    records: list[tuple[dict[str, str], Path]] = []
    for path in sorted(directory.glob(glob)):
        fields = _read_frontmatter(path)
        if fields.get("id"):
            records.append((fields, path))
    records.sort(key=lambda item: _id_sort_key(item[0]["id"]))
    return records


def _escape(text: str) -> str:
    return text.replace("|", "\\|")


def build_decisions_index() -> int:
    records = _collect(DECISIONS_DIR, "KDD-*.md")
    lines = [
        GENERATED_NOTE,
        "",
        "# Key Design Decisions (KDDs)",
        "",
        f"{len(records)} decisions. Each record carries its context, consequences, and "
        "the call or request it came from.",
        "",
        "| ID | Title | Status | Supersedes | Superseded by |",
        "| --- | --- | --- | --- | --- |",
    ]
    for fields, path in records:
        supersedes = fields.get("supersedes", "null")
        superseded_by = fields.get("superseded_by", "null")
        supersedes = "" if supersedes in ("null", "") else supersedes
        superseded_by = "" if superseded_by in ("null", "") else superseded_by
        lines.append(
            f"| [{fields['id']}]({path.name}) "
            f"| {_escape(fields.get('title', ''))} "
            f"| {fields.get('status', '')} "
            f"| {supersedes} "
            f"| {superseded_by} |"
        )
    lines.append("")
    (DECISIONS_DIR / "index.md").write_text("\n".join(lines), encoding="utf-8")
    return len(records)


def build_open_questions_index() -> int:
    records = _collect(OPEN_QUESTIONS_DIR, "OQ-*.md")
    lines = [
        GENERATED_NOTE,
        "",
        "# Open Questions (OQs)",
        "",
        f"{len(records)} open questions. Each links to the decisions it blocks and the "
        "design areas it affects.",
        "",
        "| ID | Title | Status | Blocks |",
        "| --- | --- | --- | --- |",
    ]
    for fields, path in records:
        blocks = fields.get("blocks_kdds", "")
        blocks = re.sub(r"[\[\]]", "", blocks).strip()
        lines.append(
            f"| [{fields['id']}]({path.name}) "
            f"| {_escape(fields.get('title', ''))} "
            f"| {fields.get('status', '')} "
            f"| {_escape(blocks)} |"
        )
    lines.append("")
    (OPEN_QUESTIONS_DIR / "index.md").write_text("\n".join(lines), encoding="utf-8")
    return len(records)


def main() -> int:
    kdd_count = build_decisions_index()
    oq_count = build_open_questions_index()
    print(f"Wrote decisions/index.md ({kdd_count} KDDs)")
    print(f"Wrote open-questions/index.md ({oq_count} OQs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
